### PR TITLE
Add built dist for previous PR

### PR DESCRIPTION
**Pull request by JamieLottering**
Forgot to run npm ruild and check in the dist folder for previous PR #4

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Why do you need to change the dist? The build process run before publishing.

**Comment by JamieLottering** [comment]
I suppose that’s true. I pulled 1.2.2 and didn’t see the changes but it was
because i was using single file components and forgot to change the
blueprints for those and not a dist problem

**Comment by NetanelBasal** [comment]
When you npm install the library, you should see the version with your PR. So we can cancel this?

**Comment by JamieLottering** [comment]
Ya I'll close this one and open another one for just changing the SFC blueprint, thanks!

**Pull request closed without merging**
