### PR TITLE
Typescript support

### PR DESCRIPTION
**Pull request by crispmark**
Adds typescript support so that users can specify ts default file extensions.

Summary of changes
- changed `js` to more generic `script` term in config
- added `spec` to config to allow spec configuration separate from script configuration
- added script and spec to the allowed arguments, and implemented them as config overrides
- changed all filestype.js to filestype.script
- added conditional formatting that specifies the script lang if it is not js

### CODE REVIEW

**Comment by crispmark** [comment]
#9 asked for this, but it was rejected. Hopefully this isn't too big of a change.

**Comment by NetanelBasal** [comment]
Thanks! Will check it out. This does not present any breaking changes, right? Are you just adding the option to generate ts files?

**Comment by crispmark** [comment]
Yes, there shouldn't be any difference when generating files if you haven't set spec or script.

**Comment by NetanelBasal** [comment]
Seems good to me, let me check it, and I will merge it, thanks.

**Pull request merged**
